#!/bin/sh

system_type=$(uname -s)

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submoduLe update --recursive --init

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    brew services start skhd
    brew services start yabai
    brew services start spacebar
  fi

  # yabai
  # hide desktop
  defaults write com.apple.finder CreateDesktop -bool FALSE; killall Finder

  # Disable animations when opening and closing windows.
  defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

  # Accelerated playback when adjusting the window size.
  defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

  # enable dark mode notify service
  launchctl load -w ~/Library/LaunchAgents/ke.bou.dark-mode-notify.plist

fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:basbebe/dotfiles.git"

