# Preamble
require-module plug

# Let plug.kak manage itself.
plug plug https://github.com/alexherbo2/plug.kak %{
    # Upgrade plugins
    # Install plugins and build them.
    define-command plug-upgrade -docstring 'plug-upgrade' %{
        plug-install
        plug-execute connect make install
        plug-execute lsp cargo build --release --locked
    }
}

plug-core %{
    # Options ────────────────────────────────────────────────────────────────────

    # User interface
    set-option -add global ui_options ncurses_status_on_top=yes
    set-option -add global ui_options ncurses_assistant=cat
    set-option -add global ui_options ncurses_set_title=no

    # Color scheme
    # Gruvbox theme for Kakoune
    # https://github.com/morhetz/gruvbox
    colorscheme gruvbox

    # Verbose Autoinfo
    # set-option -add global autoinfo normal

    # Highlighters
    add-highlighter global/ number-lines -relative -hlcursor
    add-highlighter global/show-matching show-matching
    add-highlighter global/show-whitespaces show-whitespaces
    add-highlighter global/ line '%val{cursor_line}' default,rgb:3c3735
    add-highlighter global/ column 81 default,rgb:3c3836
    add-highlighter global/ wrap -indent -word

    # Scroll offset
    set-option global scrolloff 5,1

    # Indentation
    # Indent with 2 spaces and make tabs 2 spaces wide.
    set-option global tabstop 2
    set-option global indentwidth 2

    # Filetype-specific
    # Makefile
    hook global WinSetOption filetype=makefile %{
        set-option buffer indentwidth 0
    }

    # indentwidth 4 Spaces
    # https://en.wikipedia.org/wiki/Indentation_(typesetting)#Indentation_in_programming
    hook global WinSetOption filetype=(fish|fsharp|java|julia|kak|kotlin|perl|php|python|rust)  %{
        set-option buffer tabstop 4
        set-option buffer indentwidth 4
    }

    # Windowing
    hook global ModuleLoaded kitty %{
        alias global terminal kitty-terminal
        alias global popup kitty-terminal # or kitty-terminal-tab
    }

    # Tools
    set-option global makecmd 'make -j 8'
    set-option global grepcmd 'rg --column --with-filename'

    # Commands ───────────────────────────────────────────────────────────────────

    # IDE
    # (needs connect.kak)

    define-command ide -params 0..1 -docstring 'ide [session-name]: Turn Kakoune into an IDE' %{
        # Session name
        try %{
            rename-session %arg{1}
    }

        # Main client
        rename-client main
        set-option global jumpclient main

        # Tools client
        new %{
            rename-client tools
            set-option global toolsclient tools
    }

        # Docs client
        new %{
            rename-client docs
            set-option global docsclient docs
    }

        # Project drawer
        broot

        # Git
    > lazygit

        # Terminal
    >

        # get focus back
        focus main
    }

    # lazygit
    # https://github.com/jesseduffield/lazygit
    define-command lazygit -params .. -docstring 'Open lazygit' %{
        + lazygit %arg{@}
    }

    alias global lg lazygit

    # Aliases ────────────────────────────────────────────────────────────────────

    # User modes
    alias global u enter-user-mode

    # Quick editing
    define-command -docstring 'Open kakrc' edit-kakoune 'edit ~/.config/kak/kakrc'
    define-command -docstring 'Open tmux.conf' edit-tmux 'edit ~/.tmux.conf'
    define-command -docstring 'Open kitty.conf' edit-kitty 'edit ~/.config/kitty/kitty.conf'
    define-command -docstring 'Open config.fish' edit-fish 'edit ~/.config/fish/config.fish'
    define-command -docstring 'Open gitconfig' edit-git 'edit ~/.gitconfig'
    define-command -docstring 'Open broot/conf.toml' edit-broot 'edit ~/.config/broot/conf.hjson'
    define-command -docstring 'Open starship.toml' edit-starship 'edit ~/.config/starship.toml'

    # Aliases
    alias global ek edit-kakoune

    # Buffers
    alias global bd delete-buffer
    alias global bf buffer-first
    alias global bl buffer-last
    alias global bo buffer-only
    alias global bo! buffer-only-force

    # Git
    alias global G lazygit

    # dotfiles
    define-command -docstring 'open dotfiles with lazygit' dotfiles '> fish -c dotfiles'

    # Mappings ───────────────────────────────────────────────────────────────────

    # Big keys
    # [Enter] [Backspace] [Tab] [Alt-Tab]
    map -docstring 'Enter command prompt' global normal <ret> :
    map -docstring 'Reduce selections to their cursor' global normal <backspace> ';'
    map -docstring 'Swap selections cursor and anchor' global normal <tab> '<a-;>'
    map -docstring 'Ensure selection cursor is after anchor' global normal <a-tab> '<a-:>'

    # Keep the jump functionality on Enter for grep and make.
    hook global WinSetOption filetype=grep %{
        map -docstring 'grep-jump' window normal <ret> ': grep-jump<ret>'
    }

    hook global WinSetOption filetype=make %{
        map -docstring 'make-jump' window normal <ret> ': make-jump<ret>'
    }

    # Control keys
    # [C-a] [C-f] [C-n] [C-o] [C-q] [C-s] [C-t] [C-w] [C-x]
    map -docstring 'Alternate buffer' global normal <c-a> ga
    map -docstring 'Find in buffer' global normal <c-f> '/(?i)\Q'
    map -docstring 'Find in buffer' global prompt <c-f> '<home>(?i)\Q<end>'
    map -docstring 'Open a new terminal window' global normal <c-n> ': connect-terminal<ret>'
    map -docstring 'Open file' global normal <c-e> ':edit<space>'
    map -docstring 'Quit' global normal <c-q> ': quit<ret>'
    map -docstring 'Save buffer' global normal <c-s> ': write<ret>'
    map -docstring 'Open a new tab' global normal <c-t> ': new<ret>'
    map -docstring 'Terminal' global normal <c-w> ': enter-user-mode terminal<ret>'
    map -docstring 'Write and quit' global normal <c-x> ': write-quit<ret>'

    # case insensitive search by default
    map global normal / "/(?i)"

    # Paths
    map -docstring 'Current buffer name' global prompt <a-?> '<c-r>%'
    map -docstring 'Current buffer directory' global prompt <a-/> '%sh(dirname "$kak_bufname")<a-!>/'

    # Select all occurrences of the current selection set.
    map -docstring 'Select all occurrences of the current selection set' global normal <a-percent> '*%s<ret>'

    # edit kakrc
    map -docstring 'Open kakrc' global user <,> ': edit-kakoune<ret>'

    # commenting
    map global user c -docstring '(un-)comment line' ': comment-line<ret>'
    map global user C -docstring '(un-)comment block' ': comment-block<ret>'

    # Mac Clipboard
    hook global NormalKey y|d|c %{
        nop %sh{
            printf %s "$kak_main_reg_dquote" | pbcopy
        }
    }

    map global user P -docstring 'Paste above' '!pbpaste<ret>'
    map global user p -docstring 'Paste below' '<a-!>pbpaste<ret>'
    map global user R -docstring 'Replace' '|pbpaste<ret>'

    # Move macros to ^
    map -docstring 'Play macro' global normal ^ q
    map -docstring 'Record macro' global normal <a-^> Q

}

# Plugins ──────────────────────────────────────────────────────────────────────

plug auto-pairs https://github.com/alexherbo2/auto-pairs.kak %{
        auto-pairs-enable
}

plug edit https://github.com/alexherbo2/edit.kak

plug capitalize-selections https://github.com/alexherbo2/capitalize-selections.kak %{
    map -docstring 'Capitalize selections' global normal <a-`> ': capitalize-selections<ret>'
}

plug connect https://github.com/alexherbo2/connect.kak %{
    # Modules
    require-module connect-fzf
    require-module connect-nnn
    require-module connect-broot

    set-option global connect_environment %{
        # export SHELL="/usr/local/bin/fish --init-command=\"set -x EDITOR :edit; set -x VISUAL :edit\""
    }
}

plug current-word-highlighter https://github.com/alexherbo2/current-word-highlighter.kak %{
        current-word-highlighter-enable
}

plug double-tap https://github.com/alexherbo2/double-tap.kak %{
    # Type "jj" to leave insert mode:
    double-tap-escape global j
}

plug execute-key https://github.com/alexherbo2/execute-key.kak

plug explore https://github.com/alexherbo2/explore.kak %{
    explore-enable

    # Configure the file explorer
    alias global explore-files fzf-files
    alias global explore-buffers fzf-buffers
}

plug-old find https://github.com/occivink/kakoune-find

plug jq https://github.com/alexherbo2/jq.kak %{
    map -docstring 'jq' global user | ': jq-prompt<ret>'
    map -docstring 'jq-selections' global user <a-|> ': jq-prompt-selections<ret>'
}

plug-old kakoune-buffers https://github.com/delapouite/kakoune-buffers %{
    # Suggested hook

    hook global WinDisplay .* info-buffers

    # Suggested mappings

    map global user b ': enter-buffers-mode<ret>' -docstring 'buffers…'
    map global user B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)…'
    map global user <a-b> ': pick-buffers<ret>' -docstring 'pick buffer…'
}

plug-old lsp https://github.com/kak-lsp/kak-lsp %{
    # set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak-lsp/kak-lsp.toml"

    # uncomment to enable debugging
    # set global lsp_cmd "kak-lsp -s %val{session} --config ~/.config/kak-lsp/kak-lsp.toml -vvv --log /tmp/kak-lsp.log"
    # eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}

    # set global lsp_diagnostic_line_error_sign '║'
    # set global lsp_diagnostic_line_warning_sign '┊'

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    map global normal <#> ': enter-user-mode lsp<ret>' -docstring 'lsp'

    set-option global lsp_auto_highlight_references true
    set global lsp_hover_anchor true
    # echo -debug "Enabling LSP for filtetype %opt{filetype}"

    hook global WinSetOption filetype=(c|cpp|cc|rust|python|java|latex|markdown) %{
        lsp-auto-hover-enable
        lsp-enable-window
    }

    hook global WinSetOption filetype=python %{
        set-option global lsp_server_configuration pyls.configurationSources=["flake8"]
    }

    hook global KakEnd .* lsp-exit
}

plug manual-indent https://github.com/alexherbo2/manual-indent.kak %{
    # Manual indent
    hook global WinCreate .* %{
        manual-indent-enable
    }

    # Remove filetype hooks
    # hook global WinSetOption filetype=.* %{
    #   manual-indent-remove-filetype-hooks
    # }
}

plug modeline-extras git/modeline-extras.kak %{
    # enable Nerd Font symbols
    set-option global modeline_nerdfont true

    # enable options
    modeline-buffer-position-enable
    modeline-git-branch-enable
    modeline-indent-enable
    modeline-lsp-enable
    # modeline-codepoint-enable

    # Git branch + Filename
    set-option global modelinefmt '{magenta+i}%opt{modeline_git_branch} {bright-blue+u}%val{bufname}{default}'
    # Position 
    set-option -add global modelinefmt ' %val{cursor_line}:%val{cursor_char_column} %opt{modeline_buffer_position}{default}'
    # Context Info + Mode Info
    set-option -add global modelinefmt ' {{context_info}} {{mode_info}}'
    # out-of-view
    set-option -add global modelinefmt ' {StatusLineMode}%opt{out_of_view_status_line}{default}'
    # lsp
    set-option -add global modelinefmt ' {DiagnosticError}%opt{modeline_lsp_err}{DiagnosticWarning}%opt{modeline_lsp_warn}{default}'
    # Filetype + Indentwidth
    set-option -add global modelinefmt ' %opt{filetype} %opt{modeline_indent}'
    # client@session
    set-option -add global modelinefmt ' {bright-cyan}%val{client}{bright-cyan+b}%val{session}'
}

plug move-line https://github.com/alexherbo2/move-line.kak %{
    map -docstring 'Move selected lines below' global normal <down> ': move-line-below<ret>'
    map -docstring 'Move selected lines above' global normal <up> ': move-line-above<ret>'
}

plug-old number-toggle https://github.com/evanrelf/number-toggle.kak %{
    set-option global number_toggle_params -hlcursor
}

plug objectify https://github.com/alexherbo2/objectify.kak

plug out-of-view https://github.com/alexherbo2/out-of-view.kak %{
    out-of-view-enable
}

plug palette https://github.com/alexherbo2/palette.kak %{
    palette-enable
}

plug-old pandoc git/pandoc.kak %{
    set-option global pandoc_options "-d default"
}

plug prelude https://github.com/alexherbo2/prelude.kak

plug replace-mode https://github.com/alexherbo2/replace-mode.kak %{
    map -docstring 'Replace' global user r ': enter-replace-mode<ret>'
}

plug search-doc https://github.com/jbomanson/search-doc.kak %{
    alias global sd search-doc
}

plug search-highlighter https://github.com/alexherbo2/search-highlighter.kak %{
    search-highlighter-enable
}

plug sleuth https://github.com/alexherbo2/sleuth.kak %{
    sleuth-enable
}

# nop plug smarttab https://github.com/andreyorst/smarttab.kak %{
#     # when `backspace' is pressed, 2 spaces are deleted at once
#     set-option global softtabstop 2

#     hook global WinSetOption filetype=.* expandtab
#     # these languages will use `noexpandtab' behavior
#     # these languages will use `expandtab' behavior
#     hook global WinSetOption filetype=(gas|go|makefile) noexpandtab
#     # these languages will use `smarttab' behavior
#     hook global WinSetOption filetype=(c|cpp) smarttab
# }

nop plug-old smooth-scroll https://github.com/caksoylar/kakoune-smooth-scroll %{
     hook global WinCreate .* %{ hook -once window WinDisplay [^*].* smooth-scroll-enable }
}

plug split-object https://github.com/alexherbo2/split-object.kak %{
    # Add text objects to the `s` command:
    map -docstring 'Split object' global prompt <a-i> '<esc>: enter-user-mode split-object<ret>'
}

plug-old sudo-write https://github.com/occivink/kakoune-sudo-write

plug surround https://github.com/alexherbo2/surround.kak %{
    ## Quoting
    map -docstring 'Surround' global normal q ': enter-user-mode surround<ret>'
    map -docstring 'Surround insert' global normal Q ': surround-enter-insert-mode<ret>'
    # map -docstring 'Surround (Replace)' global normal <a-q> ': surround-delete; enter-user-mode surround<ret>'
}

plug terminal-mode https://github.com/alexherbo2/terminal-mode.kak

plug text-objects https://github.com/alexherbo2/text-objects.kak

plug-old vertical-selection https://github.com/occivink/kakoune-vertical-selection

plug volatile-highlighter https://github.com/alexherbo2/volatile-highlighter.kak %{
    volatile-highlighter-enable
}

plug yank-ring https://github.com/alexherbo2/yank-ring.kak %{
    # Modules
    require-module yank-ring-connect

    # Enable yank-ring
    yank-ring-enable
    map global normal Y ': yank-ring<ret>'
}
