#!/bin/sh

#  https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# default management type for yabai on startup
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Set all padding and gaps (default: 0)
yabai -m config top_padding    12
yabai -m config bottom_padding 12
yabai -m config left_padding   12
yabai -m config right_padding  12
yabai -m config window_gap     8

# border settings
yabai -m config window_border               on
yabai -m config window_border_width         3
yabai -m config active_window_border_color  0xff689d6a
yabai -m config normal_window_border_color  0x88928374
yabai -m config insert_feedback_color       0xbbd79921

# on or off (default: off)
yabai -m config auto_balance off

# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.5

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set mouse drop action to swap or stack windows
yabai -m config mouse_drop_action stack

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
yabai -m config window_shadow float

# window opacity (default: off)
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# spacebar
spacebar_height=$(spacebar -m config height)
yabai -m config external_bar all:${spacebar_height}:0

# simple-bar
# yabai -m config external_bar all:28:0

# space labels
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label mail
yabai -m space 4 --label chat
yabai -m space 5 --label media
yabai -m space 6 --label cal
yabai -m space 7 --label OS
yabai -m space 8 --label misc
# yabai -m space 9
# yabai -m space 10

# window rules
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^SoftRAID$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add title="^Preferences" sticky=on layer=above manage=off
yabai -m rule --add app="^VLC$" manage=off
yabai -m rule --add app="^Deliveries$" manage=off
yabai -m rule --add app="^DarkModeBuddy$" manage=off
yabai -m rule --add app="^KeePassXC$" sticky=on layer=above manage=off
yabai -m rule --add app="^Yubi" sticky=on layer=above manage=off
yabai -m rule --add app="^ColorNavigator\ 7$" sticky=on layer=above manage=off
yabai -m rule --add app="^Firefox$" title!="^Mozilla Firefox" space="web"
yabai -m rule --add app="^Firefox$" title="^Open" manage=off layer=above
yabai -m rule --add app="^Firefox$" title="^Enter" manage=off layer=above
yabai -m rule --add app="^Tor*" space="web"
# yabai -m rule --add app="^zoom\.us$" manage=off
yabai -m rule --add app="^Chromium*" space="web"
yabai -m rule --add app="^Safari*" space="web"
yabai -m rule --add app="^VSCod*" space="^code"
yabai -m rule --add app="^RStudio*" space="^code"
yabai -m rule --add app="^MailMate*" space="mail"
yabai -m rule --add app="^mpv$" opacity=1.0

# show scratchpads and popups on top
yabai -m rule --add title="^scratchpad" manage=off sticky=on layer=above grid=4:4:1:1:2:2
yabai -m rule --add title="^popup" sticky=on layer=above grid=4:4:1:1:2:2

# adapt padding to state of stacks
yabai -m signal --add event=window_created action="~/.config/yabai/refresh.sh"
yabai -m signal --add event=window_destroyed action="~/.config/yabai/refresh.sh"
# yabai -m signal --add event=window_moved action="~/.config/yabai/refresh.sh"

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus recent &> /dev/null"
# yabai -m signal --add event=window_destroyed action='yabai -m window --focus recent'
yabai -m signal --add event=window_minimized action='yabai -m window --focus recent'

echo "yabai configuration loaded.."
