#! /bin/env sh

# if you're having troubles finding key codes for a key just type skhd --observe in a terminal and type a key. Pretty cool! Or just check the wiki.
# https://github.com/koekeishiya/skhd/issues/1

# hyper : shift + ctrl + alt + option
# meh : shift + ctrl + alt

# launch apps ——————————————————————————————————————————————————————————————————

# open terminal
# hyper - return : /Applications/kitty.app/Contents/MacOS/kitty
hyper - return : SHELL=/usr/local/bin/fish kitty --single-instance --directory=$HOME --listen-on=unix:/tmp/kitty_listen

# scratchpads
hyper - e : SCRATCHPAD_TITLE="scratchpad_editor" ~/.local/bin/scratchpad "kcr shell --session master kcr attach"
hyper - t : SCRATCHPAD_TITLE="scratchpad_terminal" ~/.local/bin/scratchpad
hyper - r : SCRATCHPAD_TITLE="scratchpad_calc" ~/.local/bin/scratchpad "r -q --no-save"

# new finder window
hyper - f : open ~

# authencicator
hyper - y : open -a 'Yubico Authenticator'

# yabai ————————————————————————————————————————————————————————————————————————

# Quickly restart the yabai launch agent
ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# navigation –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# focus window
hyper - j : yabai -m window --focus south
hyper - k : yabai -m window --focus north
hyper - h : yabai -m window --focus west || \
            { yabai -m display --focus next  || yabai -m display --focus first ; \
              yabai -m window --focus last ; }
hyper - l : yabai -m window --focus east || \
            { yabai -m display --focus prev || yabai -m display --focus last ; \
              yabai -m window --focus first ; }

# cycle through windows ([])
hyper - 0x1E : yabai -m window --focus next || yabai -m window --focus first
hyper - 0x21 : yabai -m window --focus prev || yabai -m window --focus last

# cycle through stack (hyper + ,. - karabiner trick)
0x5F : yabai -m window --focus stack.next || yabai -m window --focus stack.first
0x41 : yabai -m window --focus stack.prev || yabai -m window --focus stack.last

# cycle space
hyper - n : yabai -m space --focus next || yabai -m space --focus first
hyper - p : yabai -m space --focus prev || yabai -m space --focus last

# cycle screen
# hyper - h : { yabai -m display --focus next && yabai -m window --focus last; } || \
#   { yabai -m display --focus first && yabai -m window --focus last; }
# hyper - l : { yabai -m display --focus prev && yabai -m window --focus last; } || \
#   { yabai -m display --focus last && yabai -m window --focus last; }

# go to last space
hyper - g : yabai -m space --focus recent

# go to space
hyper - 1 : yabai -m space --focus 1
hyper - 2 : yabai -m space --focus 2
hyper - 3 : yabai -m space --focus 3
hyper - 4 : yabai -m space --focus 4
hyper - 5 : yabai -m space --focus 5
hyper - 6 : yabai -m space --focus 6
hyper - 7 : yabai -m space --focus 7
hyper - 8 : yabai -m space --focus 8
hyper - 9 : yabai -m space --focus 9
hyper - 0 : yabai -m space --focus 0


# toggles ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# toggle float
ctrl + alt - space : yabai -m window --toggle float

# toggle sticky
ctrl + alt - s : yabai -m window --toggle sticky ; \
                 yabai -m window --toggle topmost ;

# toggle split (;)
ctrl + alt - 0x29 : yabai -m window --toggle split

# toggle window zoom
ctrl + alt - z : yabai -m window --toggle zoom-parent
ctrl + alt - f : yabai -m window --toggle zoom-fullscreen
# ctrl + alt - f : yabai -m window --toggle native-fullscreen

# toggle gaps (\)
ctrl + alt - 0x2A : yabai -m space --toggle padding; yabai -m space --toggle gap

# windows ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# swap window ([])
ctrl + alt - 0x1E : yabai -m window --swap next || yabai -m window --swap first
ctrl + alt - 0x21 : yabai -m window --swap prev || yabai -m window --swap last

# move window across screen
ctrl + alt - j : yabai -m window --warp south || yabai -m window --grid 2:2:0:1:2:1 || yabai -m window --toggle split
ctrl + alt - k : yabai -m window --warp north || yabai -m window --grid 2:2:0:0:2:1 || yabai -m window --toggle split
ctrl + alt - h : yabai -m window --warp west || yabai -m window --grid 2:2:0:0:1:2 || yabai -m window --toggle split
ctrl + alt - l : yabai -m window --warp east || yabai -m window --grid 2:2:1:0:1:2 || yabai -m window --toggle split

# rotate tree (,.)
ctrl + alt - 0x2F : yabai -m space --rotate 270
ctrl + alt - 0x2B : yabai -m space --rotate 90

# change layout and ratio
ctrl + alt - 1 : yabai -m window --ratio abs:0.33 || yabai -m window --grid 1:3:0:0:1:1
ctrl + alt - 2 : yabai -m window --ratio abs:0.5 || yabai -m window --grid 1:3:1:0:1:1
ctrl + alt - 3 : yabai -m window --ratio abs:0.67 || yabai -m window --grid 1:3:2:0:1:1

# balance windows (=)
ctrl + alt - 0x18 : yabai -m space --balance

# change window size (arrow keys)
ctrl + alt - right : yabai -m window --resize right:20:0 ; yabai -m window --resize left:-20:0
ctrl + alt - left : yabai -m window --resize right:-20:0 ; yabai -m window --resize left:20:0
ctrl + alt - up : yabai -m window --resize top:0:-20 ; yabai -m window --resize bottom:0:20
ctrl + alt - down : yabai -m window --resize top:0:20 ; yabai -m window --resize bottom:0:-20

# center floating window
ctrl + alt - c : yabai -m window --grid 4:4:1:1:2:2

# stacks –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# stack window with neighbour ([])
ctrl + alt + cmd - 0x1E : yabai -m window --stack next
ctrl + alt + cmd - 0x21 : yabai -m window --stack prev

# move window into stack
# shift + ctrl + alt - k : yabai -m window --stack north
# shift + ctrl + alt - j : yabai -m window --stack south
# shift + ctrl + alt - h : yabai -m window --stack west
# shift + ctrl + alt - l : yabai -m window --stack east

# unstack window (/)
ctrl + alt + cmd - 0x2C : yabai -m window --toggle float; yabai -m window --toggle float

# screens ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# move window across display
ctrl + alt + cmd - h : { yabai -m window --display next && yabai -m display --focus next ; } || \
                       { yabai -m window --display first && yabai -m display --focus first ; }
ctrl + alt + cmd - l : { yabai -m window --display prev && yabai -m display --focus prev ; } || \
                       { yabai -m window --display last && yabai -m display --focus last ; }

# spaces –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# create new space and follow focus
shift + ctrl + alt - c : yabai -m space --create && \
                         index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                         yabai -m space --focus "${index}"

# destroy space
shift + ctrl + alt - x : yabai -m space --destroy

# switch space layout
shift + ctrl + alt - s : yabai -m space --layout stack
shift + ctrl + alt - b : yabai -m space --layout bsp

# cycle space
shift + ctrl + alt - n : yabai -m space --move next || yabai -m space --move first
shift + ctrl + alt - p : yabai -m space --move prev || yabai -m space --move last

# move space to window
shift + ctrl + alt - h : yabai -m space --display next || yabai -m space --display first
shift + ctrl + alt - l : yabai -m space --display prev || yabai -m space --display last

# move window to next space
# ctrl + alt + cmd - n : yabai -m window --space next && osascript -e 'tell application "System Events" to key code 45 using {shift down, control down, option down, command down}'
# ctrl + alt + cmd - p : yabai -m window --space prev && osascript -e 'tell application "System Events" to key code 35 using {shift down, control down, option down, command down}'
ctrl + alt + cmd - n : { yabai -m window --space next && yabai -m space --focus next ; } || \
                       { yabai -m window --space first && yabai -m space --focus first ; }
ctrl + alt + cmd - p : { yabai -m window --space prev && yabai -m space --focus prev ; } || \
                       { yabai -m window --space last && yabai -m space --focus last ; }

# move window to space and follow
# ctrl + alt + cmd - 1 : yabai -m window --space 1 && osascript -e 'tell application "System Events" to key code 18 using control down'
# ctrl + alt + cmd - 2 : yabai -m window --space 2 && osascript -e 'tell application "System Events" to key code 19 using control down'
# ctrl + alt + cmd - 3 : yabai -m window --space 3 && osascript -e 'tell application "System Events" to key code 20 using control down'
# ctrl + alt + cmd - 4 : yabai -m window --space 4 && osascript -e 'tell application "System Events" to key code 21 using control down'
# ctrl + alt + cmd - 5 : yabai -m window --space 5 && osascript -e 'tell application "System Events" to key code 23 using control down'
# ctrl + alt + cmd - 6 : yabai -m window --space 6 && osascript -e 'tell application "System Events" to key code 22 using control down'
# ctrl + alt + cmd - 7 : yabai -m window --space 7 && osascript -e 'tell application "System Events" to key code 26 using control down'
# ctrl + alt + cmd - 8 : yabai -m window --space 8 && osascript -e 'tell application "System Events" to key code 28 using control down'
# ctrl + alt + cmd - 9 : yabai -m window --space 9 && osascript -e 'tell application "System Events" to key code 25 using control down'
# ctrl + alt + cmd - 0 : yabai -m window --space 0 && osascript -e 'tell application "System Events" to key code 29 using control down'
ctrl + alt + cmd - 1 : yabai -m window --space 1 && yabai -m space --focus 1
ctrl + alt + cmd - 2 : yabai -m window --space 2 && yabai -m space --focus 2
ctrl + alt + cmd - 3 : yabai -m window --space 3 && yabai -m space --focus 3
ctrl + alt + cmd - 4 : yabai -m window --space 4 && yabai -m space --focus 4
ctrl + alt + cmd - 5 : yabai -m window --space 5 && yabai -m space --focus 5
ctrl + alt + cmd - 6 : yabai -m window --space 6 && yabai -m space --focus 6
ctrl + alt + cmd - 7 : yabai -m window --space 7 && yabai -m space --focus 7
ctrl + alt + cmd - 8 : yabai -m window --space 8 && yabai -m space --focus 8
ctrl + alt + cmd - 9 : yabai -m window --space 9 && yabai -m space --focus 9
ctrl + alt + cmd - 0 : yabai -m window --space 0 && yabai -m space --focus 0
