#!/usr/bin/env sh

# if you're having troubles finding key codes for a key just type skhd --observe in a terminal and type a key. Pretty cool! Or just check the wiki.
# https://github.com/koekeishiya/skhd/issues/1

# hyper : shift + control + option + command – set to CapsLock w/ Karabiner
# meh : shift + control + option

# Quickly restart the yabai launch agent
ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# .blacklist [
#    "kitty"
#    "terminal"
#    "qutebrowser"
# ]

#  HYPER – launch apps & window navigation  ————————————————————————————————————

# open terminal
hyper - return [
  "kitty"  : skhd --key "cmd - n"
  "finder" : (SHELL=/usr/local/bin/fish kitty --single-instance --directory=$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)') &)
  *        : ~/.local/bin/kitty-wrapper.sh
  ]

# scratchpads
hyper - e : SCRATCHPAD_TITLE="scratchpad_editor" ~/.config/skhd/scratchpad.sh fish -ilc 'kcr create --session master ; kak -c master -e "rename-client scratchpad;b *scratch*"'
hyper - t : SCRATCHPAD_TITLE="scratchpad_terminal" ~/.config/skhd/scratchpad.sh
hyper - r : SCRATCHPAD_TITLE="scratchpad_calc" ~/.config/skhd/scratchpad.sh r -q --no-save

# new finder window
hyper - f [
  "kitty"  : open $(kitty @ --to unix:/tmp/kitty_listen_$(yabai -m query --windows --space | jq -rc '.[] | select(."has-focus" == true).pid') ls | \
    jq -rc '.[] | select(.is_focused==true) | select(.is_focused==true).tabs[] | select(.is_focused==true).windows[] | select(.is_focused==true).cwd')
  "finder" : skhd --key "cmd - n"
  *        : open ~
  ]

# open mpv with url from clipboard
hyper - m : open -na /Applications/mpv.app $(pbpaste)

# open nnn window
hyper - n : (SHELL=/usr/local/bin/fish kitty --single-instance -d ~ fish -ic n &> /dev/null &)

# browser
hyper - b : open -n /Applications/Firefox.app

# authenticator
hyper - y : open -a 'Yubico Authenticator'

# toggle dark mode
hyper - d : ~/.local/bin/change-theme toggle

# windows ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# focus window (across displays)
hyper - j : skhd --key "hyper - down"
hyper - k : skhd --key "hyper - up"
hyper - h : skhd --key "hyper - left"
hyper - l : skhd --key "hyper - right"
hyper - down : yabai -m window --focus south
hyper - up : yabai -m window --focus north
hyper - left : yabai -m window --focus west || \
            { yabai -m display --focus west || yabai -m display --focus first ; }
hyper - right : yabai -m window --focus east || \
            { yabai -m display --focus east || yabai -m display --focus last ; }

# cycle through stacks '[]'
hyper - 0x21 : skhd --key "hyper - pageup"
hyper - 0x1E : skhd --key "hyper - pagedown"
hyper - pageup : yabai -m window --focus stack.prev || yabai -m window --focus stack.last
hyper - pagedown : yabai -m window --focus stack.next || yabai -m window --focus stack.first

# cycle through spaces 'hyper + ,. - karabiner trick'
0x5F :skhd --key "hyper - home"
0x41 :skhd --key "hyper - end"
hyper - home : yabai -m space --focus prev || yabai -m space --focus last
hyper - end : yabai -m space --focus next || yabai -m space --focus first

# CTRL + OPTION ————————————————————————————————————————————————————————————————

# windows ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# swap window '[]'
ctrl + alt - 0x1E : yabai -m window --swap next || yabai -m window --swap first
ctrl + alt - 0x21 : yabai -m window --swap prev || yabai -m window --swap last

# move window across screen
ctrl + alt - j : yabai -m window --warp south || yabai -m window --grid 2:2:0:1:2:1
ctrl + alt - k : yabai -m window --warp north || yabai -m window --grid 2:2:0:0:2:1
ctrl + alt - h : yabai -m window --warp west || yabai -m window --grid 2:2:0:0:1:2
ctrl + alt - l : yabai -m window --warp east || yabai -m window --grid 2:2:1:0:1:2

# change window size 'yuio'
ctrl + alt - y : yabai -m window --resize right:40:0 ; yabai -m window --resize left:-40:0
ctrl + alt - u : yabai -m window --resize top:0:40 ; yabai -m window --resize bottom:0:-40
ctrl + alt - i  : yabai -m window --resize top:0:-40 ; yabai -m window --resize bottom:0:40
ctrl + alt - o : yabai -m window --resize right:-40:0 ; yabai -m window --resize left:40:0

# rotate tree clockwise
ctrl + alt - r : yabai -m space --rotate 270

# swap window with biggest container '`'
ctrl + alt - 0x32 : yabai -m window --swap largest

# spaces –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# cycle through spaces ',.'
ctrl + alt - 0x2F : yabai -m space --focus next || yabai -m space --focus first
ctrl + alt - 0x2B : yabai -m space --focus prev || yabai -m space --focus last

# go to last space
ctrl + alt - a : yabai -m space --focus recent

# go to space
ctrl + alt - 1 : yabai -m space --focus 1
ctrl + alt - 2 : yabai -m space --focus 2
ctrl + alt - 3 : yabai -m space --focus 3
ctrl + alt - 4 : yabai -m space --focus 4
ctrl + alt - 5 : yabai -m space --focus 5
ctrl + alt - 6 : yabai -m space --focus 6
ctrl + alt - 7 : yabai -m space --focus 7
ctrl + alt - 8 : yabai -m space --focus 8
ctrl + alt - 9 : yabai -m space --focus 9
ctrl + alt - 0 : yabai -m space --focus 10
hyper - 1 : yabai -m space --focus 1
hyper - 2 : yabai -m space --focus 2
hyper - 3 : yabai -m space --focus 3
hyper - 4 : yabai -m space --focus 4
hyper - 5 : yabai -m space --focus 5
hyper - 6 : yabai -m space --focus 6
hyper - 7 : yabai -m space --focus 7
hyper - 8 : yabai -m space --focus 8
hyper - 9 : yabai -m space --focus 9
hyper - 0 : yabai -m space --focus 10

# toggles ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# toggle float
ctrl + alt - space : yabai -m window --toggle float

# toggle sticky
ctrl + alt - s : yabai -m window --toggle sticky

# toggle topmost
ctrl + alt - t : yabai -m window --toggle topmost

# toggle pip
ctrl + alt - p : yabai -m window --toggle pip

# toggle split ';'
ctrl + alt - 0x29 : yabai -m window --toggle split

# toggle border
ctrl + alt - b : yabai -m window --toggle border

# toggle window zoom
ctrl + alt - z : yabai -m window --toggle zoom-parent
ctrl + alt - f : yabai -m window --grid 1:1:0:0:1:1 || yabai -m window --toggle zoom-fullscreen
# ctrl + alt - f : yabai -m window --toggle native-fullscreen

# toggle gaps '\'
ctrl + alt - 0x2A : yabai -m space --toggle padding; yabai -m space --toggle gap

# change layout and ratio
ctrl + alt - 1 : yabai -m window --ratio abs:0.33 || yabai -m window --grid 1:3:0:0:1:1
ctrl + alt - 2 : yabai -m window --ratio abs:0.5 || yabai -m window --grid 1:3:1:0:1:1
ctrl + alt - 3 : yabai -m window --ratio abs:0.67 || yabai -m window --grid 1:3:2:0:1:1

# balance windows '='
ctrl + alt - 0x18 : yabai -m space --balance

# center floating window
ctrl + alt - c : yabai -m window --grid 4:4:1:1:2:2

# CONTROL + OPTION + COMMAND ———————————————————————————————————————————————————

# move window to next space ',.'
ctrl + alt + cmd - 0x2F : { yabai -m window --space next && yabai -m space --focus next ; } || \
                       { yabai -m window --space first && yabai -m space --focus first ; }
ctrl + alt + cmd - 0x2B : { yabai -m window --space prev && yabai -m space --focus prev ; } || \
                       { yabai -m window --space last && yabai -m space --focus last ; }

# stacks –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# stack window with neighbour '[]'
ctrl + alt + cmd - 0x1E : yabai -m window --stack next
ctrl + alt + cmd - 0x21 : yabai -m window --stack prev

# move window into stack
# meh - k : yabai -m window --stack north
# meh - j : yabai -m window --stack south
# meh - h : yabai -m window --stack west
# meh - l : yabai -m window --stack east

# unstack window ';'
ctrl + alt + cmd - 0x29 : yabai -m window --toggle float; yabai -m window --toggle float

# screens ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# move window across display
ctrl + alt + cmd - h : { yabai -m window --display next && yabai -m display --focus next ; } || \
                       { yabai -m window --display first && yabai -m display --focus first ; }
ctrl + alt + cmd - l : { yabai -m window --display prev && yabai -m display --focus prev ; } || \
                       { yabai -m window --display last && yabai -m display --focus last ; }

# move window to space and follow
ctrl + alt + cmd - 1 : yabai -m window --space 1 && yabai -m space --focus 1
ctrl + alt + cmd - 2 : yabai -m window --space 2 && yabai -m space --focus 2
ctrl + alt + cmd - 3 : yabai -m window --space 3 && yabai -m space --focus 3
ctrl + alt + cmd - 4 : yabai -m window --space 4 && yabai -m space --focus 4
ctrl + alt + cmd - 5 : yabai -m window --space 5 && yabai -m space --focus 5
ctrl + alt + cmd - 6 : yabai -m window --space 6 && yabai -m space --focus 6
ctrl + alt + cmd - 7 : yabai -m window --space 7 && yabai -m space --focus 7
ctrl + alt + cmd - 8 : yabai -m window --space 8 && yabai -m space --focus 8
ctrl + alt + cmd - 9 : yabai -m window --space 9 && yabai -m space --focus 9
ctrl + alt + cmd - 0 : yabai -m window --space 10 && yabai -m space --focus 10

# SHIFT + CONTROL + OPTION —————————————————————————————————————————————————————

# rotate tree counterclockwise
meh - r : yabai -m space --rotate 90

# create new space and follow focus
meh - c : yabai -m space --create && \
                         index="$(yabai -m query --spaces --display | jq -rc 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                         yabai -m space --focus "${index}"

# destroy space
meh - x : yabai -m space --destroy

# switch space layout
meh - s : yabai -m space --layout stack && sketchybar --trigger space_mode_change &> /dev/null
meh - b : yabai -m space --layout bsp && sketchybar --trigger space_mode_change &> /dev/null

# move space to display
meh - h : yabai -m space --display next || yabai -m space --display first
meh - l : yabai -m space --display prev || yabai -m space --display last

# move window to space
meh - 1 : yabai -m window --space 1
meh - 2 : yabai -m window --space 2
meh - 3 : yabai -m window --space 3
meh - 4 : yabai -m window --space 4
meh - 5 : yabai -m window --space 5
meh - 6 : yabai -m window --space 6
meh - 7 : yabai -m window --space 7
meh - 8 : yabai -m window --space 8
meh - 9 : yabai -m window --space 9
meh - 0 : yabai -m window --space 10
