#!/usr/bin/env sh

spacebar -m config position                    top
spacebar -m config display                     all
spacebar -m config height                      26
spacebar -m config padding_left                20
spacebar -m config padding_right               20
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15

spacebar -m config text_font                   "Mononoki:Regular:12.0"
spacebar -m config icon_font                   "JetBrainsMono Nerd Font:Regular:12.0"

spacebar -m config background_color            0xff282828
spacebar -m config foreground_color            0xffebdbb2
spacebar -m config space_icon_color            0xfffe8019
spacebar -m config space_icon_color_secondary  0xff83a598
spacebar -m config space_icon_color_tertiary   0xffb8bb26
spacebar -m config power_icon_color            0xfffabd2f
spacebar -m config battery_icon_color          0xffd75f5f
spacebar -m config dnd_icon_color              0xffd5c4a1
spacebar -m config clock_icon_color            0xff458588

spacebar -m config title                       on

spacebar -m config spaces                      on
spacebar -m config space_icon                  •
# spacebar -m config space_icon_strip                     
# spacebar -m config space_icon_strip            $(while true ; do yabai -m query --spaces | jq -r '.[] | .label' ; sleep 5 ; done)
spacebar -m config space_icon_strip            $(yabai -m query --spaces | jq -r '.[] | .label')
spacebar -m config spaces_for_all_displays     on

spacebar -m config clock                       on
spacebar -m config clock_icon                  
spacebar -m config clock_format                "%d.%m.%y %R"

spacebar -m config power                       on
spacebar -m config power_icon_strip             

spacebar -m config dnd_icon                    

spacebar -m config right_shell                 on
spacebar -m config right_shell_icon            
# spacebar -m config right_shell_command         "whoami"
spacebar -m config right_shell_command  "yabai -m query --spaces --space | jq -r '.type'"


echo "spacebar configuration loaded.."

