#!/usr/bin/env sh

limelight -m config width            2
limelight -m config radius           0
limelight -m config placement        interior
limelight -m config active_color     0xff775759
limelight -m config normal_color     0x00FFFFFF

echo "limelight configuration loaded.."
